name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # Cache Rust dependencies and tools
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Install Tauri CLI for Windows (cached)
      - name: Install Tauri CLI
        if: matrix.platform == 'windows-latest'
        shell: powershell
        run: |
          if (-not (Get-Command cargo-tauri -ErrorAction SilentlyContinue)) {
            cargo install tauri-cli@1.6.5
          } else {
            Write-Host "Tauri CLI already installed"
          }

      # Install Tauri CLI for Unix systems (cached)
      - name: Install Tauri CLI
        if: matrix.platform != 'windows-latest'
        shell: bash
        run: |
          if ! command -v cargo-tauri &> /dev/null; then
            cargo install tauri-cli@1.6.5
          else
            echo "Tauri CLI already installed"
          fi

      # Install dependencies for Linux builds
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            webkit2gtk-4.0 \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libsoup2.4-dev \
            javascriptcoregtk-4.0

      # Run Rust tests
      - name: Run Rust tests
        run: |
          cd src-tauri
          cargo test

      # Build the Tauri app
      - name: Build Tauri app
        run: |
          cd src-tauri
          cargo tauri build

      # Upload the built artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapblaster-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/*
            !src-tauri/target/release/bundle/**/*.pdb
            !src-tauri/target/release/bundle/**/*.lib