name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # Install Tauri CLI
      - name: Install Tauri CLI
        run: cargo install tauri-cli@1.6.5

      # Install dependencies for Linux builds
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      # Run Rust tests
      - name: Run Rust tests
        run: |
          cd src-tauri
          cargo test

      # Build the Tauri app
      - name: Build Tauri app
        run: |
          cd src-tauri
          cargo tauri build

      # Upload the built artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapblaster-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/*
            !src-tauri/target/release/bundle/**/*.pdb
            !src-tauri/target/release/bundle/**/*.lib